### ISSUE TITLE
Any Suggestions for setting up debugger for `C`?

### ISSUE THREAD

**Issue by asher-gh** [Pocco81/TheSupercalifragilisticexpialidociousDots#5]
Hi 
Your Config is amazing. Please would you give me some pointers to setting up a debugger (your preferred) in your setup? Like where would I add the install script? Where to save the configuration. 

Any help is greatly appreciated.

**Comment by Pocco81** [comment]
It's fairly simple. There is a part called debugging in the packer file (NvDope/initialization/init.lua) with nvim-dap and DAPInstall.nvim. nvim-dap is what you'll use for debugging and Dapinstall is for installing the debuggers like how you install language servers with the `:LspInstall` command.

For miscellaneous stuff like mappings and autocommands, can be defined from the config file.

I'll add the configs for this setup today so that you can just install a debugger and setup from the config file without too much hassle.

**Comment by asher-gh** [comment]
Wow thanks a lot

**Comment by Pocco81** [comment]
Btw I also refactored DAPInstall. You should now be able to install debuggers as instructed by DAPInstall. Once again, mappings for the debuggers are defined in the config file for NvDope :)

**Comment by asher-gh** [comment]
Where should I put the configurations for C/C++/Rust?
I tried pasting the configuration from [here](https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#ccrust-via-lldb-vscode)

Getting this error when `:lua require'dap'.continue`
```sh
No configuration found for `c`. You need to add configs to `dap.configurations.c` (See `:h dap-configuration`)
```

**Comment by Pocco81** [comment]
Ok two things:

+ you just found a bug, and I fixed it (haven't pushed yet)
+ After fixing it, I tested it out and it seems to me there is an issue with how dap calls the ccppr_vsc debugger, and `--interpreter` doesn't seem to be one of them :
```
OpenDebugAD7: ERROR: Unknown command line argument '--interpreter=mi'.
```

I followed the installation process manually and used the `--help` command to get the args from the debugger:

```
[~/.local/share/nvim/dapinstall/ccppr_vsc/extension/debugAdapters/bin] ✗ ./OpenDebugAD7 --help
OpenDebugAD7: Visual Studio Code debug adapter bridge for using Visual Studio
debug engines in VS Code

Available command line arguments:
--trace: print the requests coming from VS Code to the console.
--trace=response: print requests and response from VS Code to the console.
--engineLogging[=filePath]: Enable logging from the debug engine. If not
    specified, the log will go to the console.
--server[=port_num] : Start the debug adapter listening for requests on the
    specified TCP/IP port instead of stdin/out. If port is not specified
    TCP 4711 will be used.
--pauseForDebugger: Pause the OpenDebugAD7.exe process at startup until a
    debugger attaches.
```

So maybe it's an nvim-dap issue?

**Comment by asher-gh** [comment]
After your last commit on DAPInstall. I was able to get past the initial error. Now I'm getting this error 
```sh
Configuration:
1: Launch file
2: Attach to gdbserver :1234
Path to executable: /home/ash/Study/CS50/week5/lab5/bin/inheritance Invalid adapter `nil` for config `cppdbg`
Press ENTER or type command to continue
```

**Comment by asher-gh** [comment]
> Ok two things:
> 
> * you just found a bug, and I fixed it (haven't pushed yet)
> * After fixing it, I tested it out and it seems to me there is an issue with how dap calls the ccppr_vsc debugger. It passes some parameters to it AFAIK, being `--interpreter` one of them:
> 
> ```
> OpenDebugAD7: ERROR: Unknown command line argument '--interpreter=mi'.
> ```
> 
> I followed the installation process manually and used the `--help` command to get the args from the debugger, and it seems like the flag above does not exist...?:
> 
> ```
> [~/.local/share/nvim/dapinstall/ccppr_vsc/extension/debugAdapters/bin] ✗ ./OpenDebugAD7 --help
> OpenDebugAD7: Visual Studio Code debug adapter bridge for using Visual Studio
> debug engines in VS Code
> 
> Available command line arguments:
> --trace: print the requests coming from VS Code to the console.
> --trace=response: print requests and response from VS Code to the console.
> --engineLogging[=filePath]: Enable logging from the debug engine. If not
>     specified, the log will go to the console.
> --server[=port_num] : Start the debug adapter listening for requests on the
>     specified TCP/IP port instead of stdin/out. If port is not specified
>     TCP 4711 will be used.
> --pauseForDebugger: Pause the OpenDebugAD7.exe process at startup until a
>     debugger attaches.
> ```
> 
> So maybe it's an nvim-dap issue?

[This warning was encountered here](https://stackoverflow.com/questions/63978029/setup-lldb-debugging-with-cpp-extension-in-vscode-linux)

**Comment by Pocco81** [comment]
Hey no worry I fixed it all. Just tested the `ccppr_vsc` debugger and it works fine:

![image](https://user-images.githubusercontent.com/58336662/132966328-a7b877cd-92e1-4350-9b42-5fe298a03f7e.png)

Please note that the `ccppr_lldb` doesn't work well ATM. Please use `ccppr_vsc`, which is now fully tested and supported.

**Comment by asher-gh** [comment]
w00t. Thanks @Pocco81
