### ISSUE TITLE
catpuccin colorscheme for awesomewm

### ISSUE THREAD

**Issue by ashincoder** [Pocco81/TheSupercalifragilisticexpialidociousDots#6]
I love the catpuccin colorscheme. So I was wondering if u have tried to port it for awesomewm.
Just asking no pressure or request . :smile:

**Comment by Pocco81** [comment]
Great idea! But I don't use AwesomeWM, so in that case I might need your help to take the promo screenshots.

I think you should open an issue on Catppuccin's main repo.
